### PR TITLE
update to version 36.7.2

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
> Also please reset build/number to 0.

Nevermind, did myself directly on GH's interface. 😉

**Comment by jakirkham** [comment]
That’s neat. How did you do that?

**Comment by nicoddemus** [comment]
Just click on the "edit" button in one of the files while on the "Files changed" tab.

**Comment by jakirkham** [comment]
Neat! Thanks for the tip. :)

**Comment by nicoddemus** [comment]
My pleasure! 😁

**Comment by jakirkham** [comment]
Thanks everyone. :)

**Pull request merged**
