### PR TITLE
Release 27.1.2

### PR DESCRIPTION
**Pull request by jakirkham**
Replaces https://github.com/conda-forge/setuptools-feedstock/pull/23 ( `27.1.1` )

```rst
v27.1.2
-------

* #779 via #781: Fix circular import.

v27.1.1
-------

* #778: Fix MSVC monkeypatching.
```

### CODE REVIEW

**Comment by nicoddemus** [comment]
Shouldn't we add `--single-version-externally-managed` to the recipe btw?

**Comment by jakirkham** [comment]
Is it not there already? Note we had to switch to `build.sh` and `bld.bat` for this recipe.

**Comment by nicoddemus** [comment]
Oh my bad, sorry for the noise! Long day! 😅

**Comment by jakirkham** [comment]
No worries.

FWIW it use to not have those arguments. So this is an important and not obvious point that needs to be made with `setuptools`. Thanks for checking. 😀

**Pull request merged**
