### PR TITLE
updated to version 36.4.0 (this time with sha update)

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**

### CODE REVIEW

**Comment by jakirkham** [comment]
Sorry we dropped the ball on this one @ChrisBarker-NOAA. Looks like we have a newer version in `master` already though. Thanks for the contribution. Will try to do better next time about getting things in.

**Comment by ChrisBarker-NOAA** [comment]
oh well.

Actually, 36.8.0 is out now -- should I do a PR to update to that?

**Comment by ChrisBarker-NOAA** [comment]
just looked -- 3.6.8 was released only 15 hrs ago -- so maybe too soon?

https://github.com/pypa/setuptools/releases

**Comment by jakirkham** [comment]
Feel free to PR if you would like.

Yeah the release rate of setuptools is a bit crazy. I tried for a little while to stay on top of the latest release, but it quickly became too much. Sanity has to figure into this optimization somewhere. 😉

**Comment by ChrisBarker-NOAA** [comment]
We talked ages ago about having utilities to auto-update recipes that are building pypi releases. Anyone know what came of that?

-CHB

**Comment by ChrisBarker-NOAA** [comment]
as for this one -- maybe wait for 36.8.1 ....

**Comment by jakirkham** [comment]
> We talked ages ago about having utilities to auto-update recipes that are building pypi releases. Anyone know what came of that?

There are various command line tools or scripts to check what is out of date. There is also a script/command line tool that semi-manually creates PRs to one's own feedstocks. Though I don't think anyone has had time to do anything beyond these.

**Pull request closed without merging**
