### PR TITLE
drop certifi and wincertstore

### PR DESCRIPTION
**Pull request by graingert**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
How does this interact with pypa/setuptools#2716 ? As far as I can tell, currently `python setup.py install` hit a [codepath in easyinstall](https://github.com/pypa/setuptools/blob/6f205904ca63a91946b862068278a51dddb36cf4/setuptools/command/easy_install.py#L338) that creates a package index which [needs these dependencies](https://github.com/pypa/setuptools/blob/v49.6.0/setuptools/package_index.py#L316).

**Comment by graingert** [comment]
> How does this interact with [pypa/setuptools#2716](https://github.com/pypa/setuptools/pull/2716) ? As far as I can tell, currently `python setup.py install` hit a [codepath in easyinstall](https://github.com/pypa/setuptools/blob/6f205904ca63a91946b862068278a51dddb36cf4/setuptools/command/easy_install.py#L338) that creates a package index which [needs these dependencies](https://github.com/pypa/setuptools/blob/v49.6.0/setuptools/package_index.py#L316).

These are no longer needed because all supported pythons either use pip for setup_requires or support SSL out of the box

**Comment by mattip** [comment]
I wonder what is going on with PyPy, which implements Python 3.7.10. It does not support `ctypes.resize` which is needed for `wincertstore`, so doing `pypy setup.py install` in [pyyaml](https://github.com/yaml/pyyaml), I get this traceback
```
>python -c "import setuptools; print(setuptools.__version__)"
49.6.0.post20210628

>python -c "import sys; print(sys.version)"
3.7.10 | packaged by conda-forge | (77787b8f, Jul 30 2021, 13:01:30)
[PyPy 7.3.5 with MSC v.1916 64 bit (AMD64)]
l>python setup.py install
running install
Traceback (most recent call last):
  File "setup.py", line 295, in <module>
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "d:\miniconda\envs\matplotlib-pypy\lib-python\3\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "d:\miniconda\envs\matplotlib-pypy\lib-python\3\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "d:\miniconda\envs\matplotlib-pypy\lib-python\3\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\command\install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "d:\miniconda\envs\matplotlib-pypy\lib-python\3\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\command\easy_install.py", line 339, in finalize_options
    self.index_url, search_path=self.shadow_path, hosts=hosts,
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\package_index.py", line 316, in __init__
    and (ca_bundle or ssl_support.find_ca_bundle())
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\ssl_support.py", line 255, in find_ca_bundle
    get_win_certfile()
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\ssl_support.py", line 222, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\setuptools\ssl_support.py", line 246, in get_win_certfile
    _wincerts.addstore('CA')
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\wincertstore.py", line 411, in addstore
    self.addcerts(store.itercerts())
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\wincertstore.py", line 396, in addcerts
    for cert in certs:
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\wincertstore.py", line 325, in itercerts
    enhkey = certCtx.enhanced_keyusage()
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\wincertstore.py", line 189, in enhanced_keyusage
    keyusage = self._get_enhkey(CERT_FIND_EXT_ONLY_ENHKEY_USAGE_FLAG)
  File "d:\miniconda\envs\matplotlib-pypy\lib\site-packages\wincertstore.py", line 168, in _get_enhkey
    resize(enhkey, size.value)
  File "d:\miniconda\envs\matplotlib-pypy\lib_pypy\_ctypes\dummy.py", line 2, in dummyfunc
    raise NotImplementedError("non-implemented ctypes function")
NotImplementedError: non-implemented ctypes function
```

**Comment by graingert** [comment]
wincertstore needs to be removed because it's broken and old

**Comment by graingert** [comment]
If wincertstore isn't available setuptools uses this codepath which uses the built in python wincertstore support https://github.com/pypa/setuptools/blob/v49.6.0/setuptools/package_index.py#L321

The latest setuptools only uses this codepath

**Comment by mattip** [comment]
Ahh, cool. Indeed, if I manually delete wincertstore, `setup.py install` finishes cleanly. So then I guess the next question is why not merge this?

**Comment by graingert** [comment]
Also note that pyyaml uses `python -m build --wheel --sdist` and not `setup.py`

**Comment by mattip** [comment]
I see `setup.py install` in the [feedstock recipe](https://github.com/conda-forge/pyyaml-feedstock/blob/12d7ad1ff2adb82875e249f051dcf415800616fd/recipe/meta.yaml#L15). I am not sure why, maybe because of the extra flags to `build_ext`.
```
build:
  number: 0
  script:
    - python setup.py --with-libyaml build_ext --include-dirs="${PREFIX}/include" --library-dirs="${PREFIX}/lib"  # [unix]
    - python setup.py --with-libyaml build_ext --include-dirs="%LIBRARY_INC%" --library-dirs="%LIBRARY_LIB%"      # [win]
    - python setup.py install
    - python setup.py test

```

**Comment by graingert** [comment]
pyyaml itself uses build: `Using `build --wheel`

https://github.com/yaml/pyyaml/blob/master/packaging/build/manylinux.sh#L19

**Comment by isuruf** [comment]
Dropped in latest update

**Pull request closed without merging**
