### PR TITLE
Release 27.1.0

### PR DESCRIPTION
**Pull request by jakirkham**
```rst
v27.1.0
-------

* Introduce the (private) ``monkey`` module to encapsulate
  the distutils monkeypatching behavior.
```

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @jakirkham,

The latest `setuptools` is [28.7.1](https://pypi.python.org/pypi/setuptools), any reason why are you updating to `27.1.0`? Perhaps you need this specific version?

**Comment by nicoddemus** [comment]
Hi @jakirkham,

The latest `setuptools` is [28.7.1](https://pypi.python.org/pypi/setuptools), any reason why are you updating to `27.1.0`? Perhaps you need this specific version?

**Comment by jakirkham** [comment]
I've been trying to build every version of `setuptools`, which is a bit ridiculous as there are sometimes multiple releases in a day if not in a couple of days from each other. Still if we discover some version of `setuptools` is not workable, it is nice to be able to go back to one that is easily.

**Comment by nicoddemus** [comment]
*every* version? That's quite a [long road](https://pypi.org/project/setuptools/#history) then. 😉 

If I understand how things work correctly, we can't just open several PRs targeting different versions:

* Different PRs would all generate conflicts since they all change the same lines basically;
* Opening one PR based on another makes that other PR's build to bail out o the early, because it sees there's another PR on the queue that contains its commit.

**Comment by jakirkham** [comment]
> *every* version? That's quite a [long road](https://pypi.org/project/setuptools/#history) then. 😉 

Don't remind me. 😩 I fell a bit behind.

Actually it's not bad. I just make all the changes locally in a line and add a branch for each one. Then we just PR/merge/rebase our way through.

**Comment by nicoddemus** [comment]
> Actually it's not bad. I just make all the changes locally in a line and add a branch for each one. Then we just PR/merge/rebase our way through.

But one has to rebase/merge each individual PR for each version one at a time, waiting for it to finish/publish the packages before merging the next one, no?

**Pull request merged**
