### PR TITLE
Make package not compatible with Python 2

### LINKED ISSUE #126: Missing python2 version constraint
`conda create -c conda-forge -n test_setuptools_py27 python=2.7` installs setuptools>=45 which is incompatible with python2

### PR DESCRIPTION
**Pull request by nicoddemus**
https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v4500

We should mark the current package as "broken" after this gets merged.

Fix #126

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by ei-grad** [comment]
currently the build installing for python3 is py38_1, seems like it is ok to mark p27_0 broken, could someone do it, please? 

@nicoddemus

**Comment by nicoddemus** [comment]
Definitely, I don't have the admin privilege to do that though

cc @ocefpaf @conda-forge/core

**Comment by mbargull** [comment]
> mark 45.0.0-p27_0 broken, could someone do it, please?

done

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
